// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3SApJ8ww5NoO8bIpFhftQLU7h4O515Q',
    appId: '1:342493871296:web:7b454e3149b68206db8125',
    messagingSenderId: '342493871296',
    projectId: 'akademi-9631c',
    authDomain: 'akademi-9631c.firebaseapp.com',
    storageBucket: 'akademi-9631c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFA8lfeJjedzQB1gNqFfZl4TePtEGgzA',
    appId: '1:342493871296:android:2d7aac422449702cdb8125',
    messagingSenderId: '342493871296',
    projectId: 'akademi-9631c',
    storageBucket: 'akademi-9631c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-JJb7fDj690NMxBjvQX6SQ3LiSzC5oE',
    appId: '1:342493871296:ios:ac14999d39f526c8db8125',
    messagingSenderId: '342493871296',
    projectId: 'akademi-9631c',
    storageBucket: 'akademi-9631c.appspot.com',
    iosClientId:
        '342493871296-48b4qtkqrm5vb7e2qeue8rl2j0pekn0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.appjam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-JJb7fDj690NMxBjvQX6SQ3LiSzC5oE',
    appId: '1:342493871296:ios:ac14999d39f526c8db8125',
    messagingSenderId: '342493871296',
    projectId: 'akademi-9631c',
    storageBucket: 'akademi-9631c.appspot.com',
    iosClientId:
        '342493871296-48b4qtkqrm5vb7e2qeue8rl2j0pekn0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.appjam',
  );
}
